// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.solution.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Breed = "something",
                            Gender = "male",
                            Name = "A dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 40,
                            Breed = "something",
                            Gender = "Male",
                            Name = "Spot"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 45,
                            Breed = "something",
                            Gender = "female",
                            Name = "Phil"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 34,
                            Breed = "something",
                            Gender = "male",
                            Name = "bob"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "something",
                            Gender = "female",
                            Name = "dontknow"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 200,
                            Breed = "something",
                            Gender = "???",
                            Name = "nope"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
